version: '3.8'

services:

  backend:
    image: nithiyab12/mean-backend:latest
    container_name: mean_backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # The backend will automatically fall back to your MongoDB Atlas URI defined in db.config.js
    networks:
      - mean-network

  frontend:
    image: nithiyab12/mean-frontend:latest
    container_name: mean_frontend
    ports:
      - "50266:80"
    depends_on:
      - backend
    networks:
      - mean-network

networks:
  mean-network:
    driver: bridge
